### ISSUE TITLE
Implementing DTM from scratch

### ISSUE THREAD

**Issue by eubinecto** [eubinecto/likelion-nlp#2]
어떤 튜토리얼을 소스로 만들면 좋을까? 

Movies dataset을 기반으로 만들면 될듯!

## To-do's
- [ ] `build_dtm` 스크립트 완성하기
- [ ] TFIDF의 필요성을 느끼게 해주는 예시찾기 - 주로.. stopwords 위주로 찾으면 될듯? e.g. `the`
- [ ] Google collab으로 만들기! (일단 현재로서는, 설명은 생략하는 것이 좋을 것!)
- [ ] 슬라이드에서 언급할만한 부분들?

**Comment by eubinecto** [comment]
## DTM을 어떻게 만들었더라?

이거 nltk로 했었나? 아니면 gensim으로 했었나?
